FROM ethereum/client-go:v1.10.7

CMD ["--dev", \
     "--dev.period", "1", \
     "--http", \
     "--http.addr", "0.0.0.0", \
     "--http.api", "eth,net,web3,personal,debug", \
     "--verbosity", "3"]
